language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script:
  - npm install -g grunt-cli grunt-phplint --save-dev
  - npm install
script:
  - grunt lint
notifications:
  slack: sosifam:fENoi7OkKYGxig7zErxFPehK