language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_script:
  - npm install grunt grunt-cli grunt-phplint --save-dev
script:
  - grunt lint
notifications:
  slack: sosifam:fENoi7OkKYGxig7zErxFPehK